site_site_homepage:
    path:     /
    defaults: { _controller: SiteSiteBundle:Default:index }

site_site_sign_up:
    path:     /inscription
    defaults: { _controller: SiteSiteBundle:Users:inscription }

site_site_sign_in:
    path:     /connexion
    defaults: { _controller: SiteSiteBundle:Users:connexion }

site_site_disconnect:
    path:     /deconnexion
    defaults: { _controller: SiteSiteBundle:Users:deconnexion }

site_site_profil:
    path:    /menu/profil/
    defaults: { _controller: SiteSiteBundle:Users:edit}

site_site_menu:
    path:     /menu/
    defaults: { _controller: SiteSiteBundle:Menu:accueil}

site_site_shop:
    path:     /menu/shop
    defaults: { _controller: SiteSiteBundle:Shop:commande}

site_site_panier:
    path:     /menu/shop/panier
    defaults: { _controller: SiteSiteBundle:Shop:panier}

site_site_admin:
    path:     /administration
    defaults: { _controller: SiteSiteBundle:Admin:editUsers}


