<?php

namespace Site\SiteBundle\Repository;

/**
 * ENtityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ENtityRepository extends \Doctrine\ORM\EntityRepository
{
}
