<?php

namespace Site\SiteBundle\Repository;

/**
 * Im1920Prod_cmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Im1920Prod_cmdRepository extends \Doctrine\ORM\EntityRepository
{
}
