<?php

namespace Site\SiteBundle\Repository;

/**
 * Im1920UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Im1920UtilisateursRepository extends \Doctrine\ORM\EntityRepository
{
}


