<?php

namespace Site\SiteBundle\Repository;

/**
 * Im1920CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Im1920CommandRepository extends \Doctrine\ORM\EntityRepository
{
}
