<?php

namespace Site\SiteBundle\Repository;

/**
 * SignUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignUpRepository extends \Doctrine\ORM\EntityRepository
{
}

