<?php

namespace Site\SiteBundle\Repository;

/**
 * SignInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignInRepository extends \Doctrine\ORM\EntityRepository
{
}

